source 'https://rubygems.org'

# pro gems:
gem 'concurrent-ruby'
gem 'concurrent-ruby-ext'
gem 'connection_pool'
gem 'disque'
gem 'semantic_logger'
gem 'sequel'
gem 'sequel_pg'

# development:
gem 'byebug'

