require_relative 'helpers/paths_resolver'

libs = ["# generated by pro - any change will be overwritten",
        "# checkout file tools/starter/frontend_init.rb",
        "require 'imba'", "global.L = require 'lodash'"]
list = ["services/pro/index.coffee"] +
  PathsResolver.resolve('scss', sort: true) +
  PathsResolver.resolve('(jpe?g|png|gif|svg)') +
  PathsResolver.resolve('(imba|coffee)', blacklist: ['^services/pro/.*'], sort: :leafs_first) +
  ['services/pro/start.imba']

list.map! do |line|
  "require '../../#{line}'"
end

IO.write 'services/pro/init_order.coffee', (libs + list).join("\n")
