# generated by pro - any change will be overwritten
# checkout file framework/tools/starter/frontend_init.rb
require 'imba'
global.L = require 'lodash'
require '../../framework/services/index.coffee'
require '../../framework/app/app.imba'
require '../../app/identities/identities.imba'
require '../../services/init.coffee'
require '../services/start.imba'